### PR TITLE
 1.8-release candidate 1

### PR DESCRIPTION
**Pull request by mikfhan**
Testing in progress; I have added links to latest curseforge and project pages where players can test the new config panel and report any issues. If none are found and no further code is changed after February 10th I think this candidate 1 should be good enough for 1.8-release.

### CODE REVIEW

**Comment by mikfhan** [comment]
Two players mention they are bombarded with LUA script errors if they install [1.8-release candidate 1](https://github.com/int3ro/Nameplates_Threat/archive/eba8fc101b6ade506fbf7d8f8d94de49e66527ee.zip) and rename folder to NamePlatesThreat, but I am unable to reproduce this with a blank AddOns folder, regardless of using a new or old character on PTR Brill or EnEU Terrokar realms, and regardless of what AddOn settings I have in the config panel. I also typed /console scripterrors 1 to be sure.

Any help testing this will be greatly appreciated (I have battletag Sjakal#2448 if real-time chat helps); otherwise we may have to assume they installed the AddOn incorrectly or another AddOn is interfering with this latest version somehow, causing errors we cannot reproduce or fix until after 1.8-release.

**Comment by mikfhan** [comment]
Hah, think I have the explanation now: the addon folder MUST be "NamePlatesThreat" with a capital P, otherwise the GetAddOnMetadata calls will fail to return anything, causing nil reference LUA errors.

So when merging and creating 1.8-release, please ensure the folder name is "NamePlatesThreat". If that is not possible to rename going forward, just let me know and I may be able to change some code.

**Comment by mikfhan** [comment]
I have created 1.8-release now, but am unable/unsure how to update CurseForge project and addon pages with a new zip-file. Maybe the description of colors and config panels could also do with an update.

**Comment by int3ro** [comment]
Hey,

sorry for the inactivity. I'm not actively playing currently and just came back from a long vacation.

Thanks for maintaining the project. If you tell me your username on curseforge.com I'll add you as a project member there aswell. That would allow you to change the project description.

Cheers

**Pull request merged**
